from pathlib import Path

def patch(path, old, new, required=True, count=1):
    p=Path(path); s=p.read_text(encoding='utf-8')
    if old not in s:
        if required: raise SystemExit(f'v4.3 patch target not found: {path}: {old[:120]!r}')
        print('v4.3 skip',path,old[:70]); return
    s=s.replace(old,new,count)
    p.write_text(s,encoding='utf-8')

# ---------- Main: bottom navigation, Ahl al-Bayt shortcut, timed relock, privacy gates ----------
main='app/src/main/java/com/rafat/munasabati/MainActivity.java'
patch(main,'    private Button dateFilter,todayBtn,listBtn,calendarBtn,favBtn;','    private Button dateFilter,todayBtn,listBtn,calendarBtn,favBtn;\n    private Button[] bottomNav;',required=False)
patch(main,'    @Override protected void onStart(){super.onStart();registerCalendarObserver();}','    @Override protected void onStart(){super.onStart();maybeRelock();registerCalendarObserver();}',required=False)
patch(main,'    @Override protected void onStop(){unregisterCalendarObserver();super.onStop();}','    @Override protected void onStop(){unregisterCalendarObserver();super.onStop();}\n    @Override public void onUserLeaveHint(){super.onUserLeaveHint();V43Prefs.setLastBackground(this,System.currentTimeMillis());}\n    private void maybeRelock(){if(!getSharedPreferences("munasabati_v4",0).getBoolean("lock_enabled",false))return;long last=V43Prefs.lastBackground(this),timeout=V43Prefs.autoLockMs(this);if(last<=0)return;if(System.currentTimeMillis()-last>=timeout){V43Prefs.setLastBackground(this,0L);startActivity(new Intent(this,LauncherActivity.class).putExtra("unlock_only",true));}}',required=False)
patch(main,'        AutoBackupScheduler.schedule(this);CalendarSyncScheduler.schedule(this);','        AutoBackupScheduler.schedule(this);CalendarSyncScheduler.schedule(this);AhlBaytReminderScheduler.schedule(this);',required=False)
patch(main,'Button v4=heroIcon("✦");top.addView(v4,new LinearLayout.LayoutParams(dp(46),dp(44)));v4.setOnClickListener(v->startActivity(new Intent(this,ModernCenterActivity.class)));','Button v4=heroIcon("✦");top.addView(v4,new LinearLayout.LayoutParams(dp(46),dp(44)));v4.setOnClickListener(v->startActivity(new Intent(this,ModernCenterActivity.class)));Button sacred=heroIcon("☾");top.addView(sacred,new LinearLayout.LayoutParams(dp(46),dp(44)));sacred.setOnClickListener(v->startActivity(new Intent(this,AhlBaytCenterActivity.class)));',required=False)
patch(main,'root.addView(modes,margin(-1,dp(48),0,0,0,dp(7)));','modes.setVisibility(View.GONE);root.addView(modes,margin(-1,dp(48),0,0,0,dp(7)));',required=False)
patch(main,'root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));\n        setContentView(root);','root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));addBottomNavigation(root);\n        setContentView(root);',required=False)
patch(main,'    private Button modeButton(String s){',r'''    private void addBottomNavigation(LinearLayout root){
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(5),dp(5),dp(5),dp(5));nav.setBackground(round(ModernUi.surface(this),22));nav.setElevation(dp(5));bottomNav=new Button[4];bottomNav[0]=navButton("⌂\n"+tr("الرئيسية","Home"));bottomNav[1]=navButton("▦\n"+tr("التقويم","Calendar"));bottomNav[2]=navButton("≡\n"+tr("المناسبات","Events"));bottomNav[3]=navButton("•••\n"+tr("المزيد","More"));for(Button b:bottomNav)nav.addView(b,new LinearLayout.LayoutParams(0,dp(58),1));bottomNav[0].setOnClickListener(v->setMode(MODE_TODAY));bottomNav[1].setOnClickListener(v->setMode(MODE_CALENDAR));bottomNav[2].setOnClickListener(v->setMode(MODE_LIST));bottomNav[3].setOnClickListener(v->startActivity(new Intent(this,ModernCenterActivity.class)));root.addView(nav,margin(-1,dp(68),0,dp(6),0,0));updateBottomNavigation();
    }
    private Button navButton(String s){Button b=button(s,muted,Color.TRANSPARENT,11);b.setGravity(Gravity.CENTER);b.setTypeface(null,Typeface.BOLD);return b;}
    private void updateBottomNavigation(){if(bottomNav==null)return;int active=mode==MODE_TODAY?0:mode==MODE_CALENDAR?1:mode==MODE_LIST?2:-1;for(int i=0;i<bottomNav.length;i++){boolean on=i==active;bottomNav[i].setTextColor(on?primary:muted);bottomNav[i].setBackground(round(on?ModernUi.alpha(primary,20):Color.TRANSPARENT,15));}}

    private Button modeButton(String s){''',required=False)
patch(main,'private void updateModeButtons(){if(todayBtn==null)return;Button[] bs={todayBtn,listBtn,calendarBtn,favBtn};for(int i=0;i<bs.length;i++){boolean on=mode==i;bs[i].setTextColor(on?primary:muted);bs[i].setBackground(round(on?Color.rgb(229,242,240):Color.TRANSPARENT,12));}}','private void updateModeButtons(){if(todayBtn==null)return;Button[] bs={todayBtn,listBtn,calendarBtn,favBtn};for(int i=0;i<bs.length;i++){boolean on=mode==i;bs[i].setTextColor(on?primary:muted);bs[i].setBackground(round(on?Color.rgb(229,242,240):Color.TRANSPARENT,12));}updateBottomNavigation();}',required=False)
patch(main,'    private void shareEvent(EventStore.Event e,long time){StringBuilder s=new StringBuilder();','    private void shareEvent(EventStore.Event e,long time){if(V43Prefs.protectExports(this)){PrivacyGate.run(this,()->shareEventUnlocked(e,time));return;}shareEventUnlocked(e,time);}\n    private void shareEventUnlocked(EventStore.Event e,long time){StringBuilder s=new StringBuilder();',required=False)
patch(main,'    private void showDataTools(){String[] items=','    private void showDataTools(){if(V43Prefs.protectExports(this)){PrivacyGate.run(this,this::showDataToolsUnlocked);return;}showDataToolsUnlocked();}\n    private void showDataToolsUnlocked(){String[] items=',required=False)
patch(main,'    private void openAttachment(EventStore.Event e){try{Intent i=new Intent(Intent.ACTION_VIEW);','    private void openAttachment(EventStore.Event e){if(V43Prefs.protectAttachments(this)){PrivacyGate.run(this,()->openAttachmentUnlocked(e));return;}openAttachmentUnlocked(e);}\n    private void openAttachmentUnlocked(EventStore.Event e){try{Intent i=new Intent(Intent.ACTION_VIEW);',required=False)

# ---------- Editor: progressive disclosure, Smart Reminder, alert profiles ----------
edit='app/src/main/java/com/rafat/munasabati/EditEventActivity.java'
patch(edit,'    private Spinner category,recurrence,colorSpinner;','    private Spinner category,recurrence,colorSpinner,alertProfile;',required=False)
patch(edit,'addDetailsCard();addDateCard();addReminderCard();addSyncCard();addAttachmentCard();addLocationCard();V4EditorHooks.decorate(this,root,id,category,reminderChecks,reminderValues);addBottomActions();',r'''addDetailsCard();addDateCard();addReminderCard();Button advanced=outlineButton(tr("⌄  خيارات متقدمة","⌄  Advanced options"));root.addView(advanced,margin(-1,dp(50),0,0,0,dp(10)));int advStart=root.getChildCount();addSyncCard();addAttachmentCard();addLocationCard();V4EditorHooks.decorate(this,root,id,category,reminderChecks,reminderValues);int advEnd=root.getChildCount();boolean[] advShown={id!=0};for(int i=advStart;i<advEnd;i++)root.getChildAt(i).setVisibility(advShown[0]?View.VISIBLE:View.GONE);advanced.setText(advShown[0]?tr("⌃  إخفاء الخيارات المتقدمة","⌃  Hide advanced options"):tr("⌄  خيارات متقدمة","⌄  Advanced options"));advanced.setOnClickListener(v->{advShown[0]=!advShown[0];for(int i=advStart;i<advEnd;i++)root.getChildAt(i).setVisibility(advShown[0]?View.VISIBLE:View.GONE);advanced.setText(advShown[0]?tr("⌃  إخفاء الخيارات المتقدمة","⌃  Hide advanced options"):tr("⌄  خيارات متقدمة","⌄  Advanced options"));});addBottomActions();''',required=False)
patch(edit,'        LinearLayout strong=new LinearLayout(this);',r'''        Button smart=outlineButton(tr("✨  استخدم Smart Reminder لهذه الفئة","✨  Use Smart Reminder for this category"));card.addView(smart,margin(-1,dp(50),0,dp(9),0,0));smart.setOnClickListener(v->applySmartReminders());
        TextView profileLabel=fieldLabel(tr("درجة التنبيه","Alert profile"));card.addView(profileLabel);alertProfile=new Spinner(this);alertProfile.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ar()?new String[]{"عادي","مهم","عاجل"}:new String[]{"Normal","Important","Urgent"}));card.addView(alertProfile,new LinearLayout.LayoutParams(-1,dp(50)));
        LinearLayout strong=new LinearLayout(this);''',required=False)
patch(edit,'strongAlertSwitch.setChecked(e.strongAlert);calendarSyncSwitch.setChecked(e.calendarSync);','strongAlertSwitch.setChecked(e.strongAlert);String ap=V43Prefs.alertProfile(this,e.id);if(alertProfile!=null)alertProfile.setSelection("urgent".equals(ap)?2:"important".equals(ap)?1:0);calendarSyncSwitch.setChecked(e.calendarSync);',required=False)
patch(edit,'e.favorite=favoriteBox.isChecked();e.pinned=pinnedBox.isChecked();e.strongAlert=strongAlertSwitch.isChecked();e.calendarSync=calendarSyncSwitch.isChecked();','e.favorite=favoriteBox.isChecked();e.pinned=pinnedBox.isChecked();String alertMode=alertProfile==null?"normal":(alertProfile.getSelectedItemPosition()==2?"urgent":alertProfile.getSelectedItemPosition()==1?"important":"normal");e.strongAlert=!"normal".equals(alertMode)||strongAlertSwitch.isChecked();e.calendarSync=calendarSyncSwitch.isChecked();',required=False)
patch(edit,'EventStore.save(this,all);V4EditorHooks.afterSave(this,e);ReminderScheduler.schedule(this,e);','EventStore.save(this,all);V43Prefs.setAlertProfile(this,e.id,alertMode);V4EditorHooks.afterSave(this,e);ReminderScheduler.schedule(this,e);',required=False)
patch(edit,'    private void ensureCalendarReady(){',r'''    private void applySmartReminders(){String code=Categories.CODES[category.getSelectedItemPosition()];HashSet<Integer> wanted=new HashSet<>();for(int x:SmartReminderRules.values(this,code))wanted.add(x);for(int i=0;i<reminderValues.length;i++)reminderChecks[i].setChecked(wanted.contains(reminderValues[i]));toast(tr("تم تطبيق: ","Applied: ")+SmartReminderRules.summary(this,code));}

    private void ensureCalendarReady(){''',required=False)

# ---------- Settings: refined control hub and haptic intensity ----------
settings='app/src/main/java/com/rafat/munasabati/SettingsActivity.java'
patch(settings,'addAppearanceCard();addInteractionCard();addAhlBaytCalendarCard();addCalendarCard();addNotificationCard();addBackupCard();addAboutCard();','addAppearanceCard();addInteractionCard();addRefinedControlsCard();addAhlBaytCalendarCard();addCalendarCard();addNotificationCard();addBackupCard();addAboutCard();',required=False)
patch(settings,'    private void addAhlBaytCalendarCard(){',r'''    private void addRefinedControlsCard(){LinearLayout card=card(tr("تجربة v4.3 المحسّنة","v4.3 refined experience"),"✦",tr("اختصارات للتحكم في التنبيه والذكاء والخصوصية","Quick controls for alerts, smart rules and privacy"));TextView h=text(tr("شدة اللمس","Haptic strength"),13,true);card.addView(h);Spinner hs=new Spinner(this);hs.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ar()?new String[]{"إيقاف","خفيف","متوسط"}:new String[]{"Off","Light","Medium"}));hs.setSelection(UiFeedback.hapticLevel(this));card.addView(hs,new LinearLayout.LayoutParams(-1,dp(48)));hs.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){boolean first=true;public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(first){first=false;return;}UiFeedback.setHapticLevel(SettingsActivity.this,pos);}public void onNothingSelected(AdapterView<?>p){}});Button smart=outlineButton(tr("✨ إعداد قواعد Smart Reminder","✨ Smart Reminder rules"));card.addView(smart,margin(-1,dp(48),0,dp(8),0,0));smart.setOnClickListener(v->startActivity(new Intent(this,SmartReminderSettingsActivity.class)));Button alerts=outlineButton(tr("🔔 فحص واختبار Strong Alert","🔔 Strong Alert diagnostics"));card.addView(alerts,margin(-1,dp(48),0,dp(7),0,0));alerts.setOnClickListener(v->startActivity(new Intent(this,AlertDiagnosticsActivity.class)));Button privacy=outlineButton(tr("🔐 الخصوصية والقفل التلقائي","🔐 Privacy & auto-lock"));card.addView(privacy,margin(-1,dp(48),0,dp(7),0,0));privacy.setOnClickListener(v->startActivity(new Intent(this,PrivacySettingsActivity.class)));Button sacred=outlineButton(tr("☾ تقويم أهل البيت عليهم السلام","☾ Ahl al-Bayt Calendar"));card.addView(sacred,margin(-1,dp(48),0,dp(7),0,0));sacred.setOnClickListener(v->startActivity(new Intent(this,AhlBaytCenterActivity.class)));}

    private void addAhlBaytCalendarCard(){''',required=False)

# ---------- Sync center: retry / force push / explicit conflict resolution ----------
sync='app/src/main/java/com/rafat/munasabati/SyncCenterActivity.java'
patch(sync,'Button imp=outlineButton(tr("＋  استيراد أحداث Google / Outlook","＋  Import Google / Outlook events"));card.addView(imp,margin(-1,dp(52),0,dp(8),0,0));imp.setOnClickListener(v->loadImportEvents());',r'''Button imp=outlineButton(tr("＋  استيراد أحداث Google / Outlook","＋  Import Google / Outlook events"));card.addView(imp,margin(-1,dp(52),0,dp(8),0,0));imp.setOnClickListener(v->loadImportEvents());Button retry=outlineButton(tr("↻  إعادة المحاولة","↻  Retry sync"));card.addView(retry,margin(-1,dp(48),0,dp(7),0,0));retry.setOnClickListener(v->syncNow());Button force=outlineButton(tr("↑  فرض رفع نسخة مناسبـاتي","↑  Force push Munasabati"));card.addView(force,margin(-1,dp(48),0,dp(7),0,0));force.setOnClickListener(v->forcePushAll());if(SyncConflictStore.count(this)>0){Button conflicts=outlineButton(tr("⚠  حل التعارضات (","⚠  Resolve conflicts (")+SyncConflictStore.count(this)+")");card.addView(conflicts,margin(-1,dp(48),0,dp(7),0,0));conflicts.setOnClickListener(v->startActivity(new Intent(this,SyncConflictActivity.class)));}''',required=False)
patch(sync,'    private void loadImportEvents(){',r'''    private void forcePushAll(){if(!CalendarIntegration.hasPermission(this)){toast(tr("صلاحية التقويم مطلوبة","Calendar permission required"));return;}showSkeleton();new Thread(()->{CalendarIntegration.SyncResult r=CalendarIntegration.forcePushAll(this);runOnUiThread(()->{renderBody();toast(r.hasErrors()?tr("اكتمل الرفع مع ملاحظات","Force push completed with notes"):tr("تم رفع نسخة مناسبـاتي","Munasabati version pushed"));});},"calendar-force-push").start();}

    private void loadImportEvents(){''',required=False)

# ---------- Sync engine: preserve conflicts until user chooses ----------
cal='app/src/main/java/com/rafat/munasabati/CalendarIntegration.java'
patch(cal,r'''                    }else{
                        result.conflicts++;result.errors.add(e.title+": "+AppSettings.tr(c,"تعارض تعديل — تم اعتماد نسخة التقويم الخارجي","Edit conflict — external calendar version was used"));
                        pullExternal(e,ext);reschedule(c,e);e.calendarFingerprint=localFingerprint(e);result.pulled++;changed=true;
                    }
                    kept.add(e);''',r'''                    }else{
                        result.conflicts++;SyncConflictStore.add(c,e,ext);result.errors.add(e.title+": "+AppSettings.tr(c,"تعارض تعديل — يحتاج قرارك من مركز المزامنة","Edit conflict — waiting for your choice in Sync Center"));kept.add(e);continue;
                    }
                    kept.add(e);''',required=True)
patch(cal,'    public static boolean pushLocalChange(Context c,long localEventId){',r'''    public static boolean forcePush(Context c,long localEventId){if(!hasPermission(c))return false;EventStore.Event e=EventStore.find(c,localEventId);if(e==null||!e.calendarSync)return false;long target=e.calendarId>0?e.calendarId:selectedCalendarId(c);if(target<=0)return false;boolean ok=pushEvent(c,e,target);if(ok)EventStore.replace(c,e);return ok;}
    public static boolean resolveConflictUseExternal(Context c,long localEventId,long externalId){if(!hasPermission(c))return false;EventStore.Event e=EventStore.find(c,localEventId);ExternalEvent ext=queryExternalById(c,externalId);if(e==null||ext==null||ext.deleted)return false;pullExternal(e,ext);reschedule(c,e);e.calendarFingerprint=externalFingerprint(ext);EventStore.replace(c,e);return true;}
    public static SyncResult forcePushAll(Context c){SyncResult r=new SyncResult();if(!hasPermission(c)){r.errors.add(AppSettings.tr(c,"صلاحية التقويم غير متاحة","Calendar permission is not available"));recordResult(c,r);return r;}List<EventStore.Event> all=new ArrayList<>(EventStore.load(c));long def=selectedCalendarId(c);for(EventStore.Event e:all){if(!e.calendarSync)continue;long target=e.calendarId>0?e.calendarId:def;if(target<=0){r.errors.add(e.title+": "+AppSettings.tr(c,"لا يوجد تقويم محدد","No selected calendar"));continue;}if(pushEvent(c,e,target))r.pushed++;else r.errors.add(e.title+": "+AppSettings.tr(c,"فشل الرفع","Push failed"));}EventStore.save(c,all);recordResult(c,r);return r;}

    public static boolean pushLocalChange(Context c,long localEventId){''',required=True)

print('v4.3 refined experience patches applied')
