from pathlib import Path

MODERN=Path('app/src/main/java/com/rafat/munasabati/ModernUi.java')
MODERN.write_text(r'''package com.rafat.munasabati;

import android.app.Activity;import android.content.Context;import android.content.res.ColorStateList;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.*;import android.os.Build;import android.view.*;import android.view.animation.OvershootInterpolator;import android.widget.*;import java.util.WeakHashMap;

/** Fresh Identity C: calm green surfaces, mint depth and coral action feedback. */
public final class ModernUi {
    private static final WeakHashMap<View,Boolean> DECORATED=new WeakHashMap<>();private static final WeakHashMap<Activity,Boolean> ANIMATED=new WeakHashMap<>();private static final WeakHashMap<View,int[]> SAFE_BASE=new WeakHashMap<>();
    public static void apply(Activity a){if(a==null||a instanceof StrongAlertActivity)return;boolean dark=isDark(a);int primary=V4Theme.primary(a);Window w=a.getWindow();try{if(Build.VERSION.SDK_INT>=35){w.setDecorFitsSystemWindows(false);w.setStatusBarColor(Color.TRANSPARENT);w.setNavigationBarColor(Color.TRANSPARENT);if(Build.VERSION.SDK_INT>=29)w.setNavigationBarContrastEnforced(false);WindowInsetsController c=w.getInsetsController();if(c!=null){int mask=WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS;int app=dark?0:mask;c.setSystemBarsAppearance(app,mask);}w.getDecorView().setBackgroundColor(screenBackground(a));}else{w.setStatusBarColor(primary);w.setNavigationBarColor(dark?Color.rgb(8,34,29):V4Theme.ivory());if(Build.VERSION.SDK_INT>=26){int f=w.getDecorView().getSystemUiVisibility();if(dark)f&=~View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;else f|=View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;w.getDecorView().setSystemUiVisibility(f);}}}catch(Exception ignored){}installSafeArea(a);View root=w.getDecorView().findViewById(android.R.id.content);if(root==null)root=w.getDecorView();decorateTree(root,primary,dark);if(UiFeedback.motionEnabled(a)&&!ANIMATED.containsKey(a)){ANIMATED.put(a,true);root.setAlpha(0f);root.setTranslationY(dp(a,7));root.animate().alpha(1f).translationY(0f).setDuration(210).start();}}
    public static void installSafeArea(Activity a){if(a==null||a instanceof StrongAlertActivity||Build.VERSION.SDK_INT<35)return;try{Window w=a.getWindow();w.setDecorFitsSystemWindows(false);View content=w.getDecorView().findViewById(android.R.id.content);if(content==null)return;int[] base=SAFE_BASE.get(content);if(base==null){base=new int[]{content.getPaddingLeft(),content.getPaddingTop(),content.getPaddingRight(),content.getPaddingBottom()};SAFE_BASE.put(content,base);}final int[] b=base;content.setBackgroundColor(screenBackground(a));content.setOnApplyWindowInsetsListener((v,insets)->{try{android.graphics.Insets bars=insets.getInsetsIgnoringVisibility(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars()|WindowInsets.Type.displayCutout());v.setPadding(b[0]+bars.left,b[1]+bars.top,b[2]+bars.right,b[3]+bars.bottom);}catch(Exception ignored){}return insets;});content.requestApplyInsets();}catch(Exception ignored){}}
    public static void modernCard(View v){if(v==null)return;try{v.setElevation(dp(v.getContext(),2));v.setClipToOutline(false);}catch(Exception ignored){}}
    public static GradientDrawable fieldBackground(Context c,int primary){GradientDrawable g=new GradientDrawable();g.setColor(isDark(c)?Color.rgb(17,55,48):Color.rgb(250,252,250));g.setCornerRadius(dp(c,16));g.setStroke(dp(c,1),alpha(isDark(c)?V4Theme.mint():V4Theme.secondary(),isDark(c)?92:48));return g;}
    public static int screenBackground(Context c){return isDark(c)?Color.rgb(8,34,29):V4Theme.ivory();}
    public static int surface(Context c){return isDark(c)?Color.rgb(15,57,49):Color.WHITE;}
    public static int surfaceSoft(Context c){return isDark(c)?Color.rgb(20,66,57):Color.rgb(241,249,246);}
    public static int ink(Context c){return isDark(c)?Color.rgb(241,249,246):Color.rgb(15,77,67);}
    public static int muted(Context c){return isDark(c)?Color.rgb(174,207,197):Color.rgb(96,126,118);}
    public static boolean isDark(Context c){return (c.getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;}
    private static void decorateTree(View v,int primary,boolean dark){if(v==null)return;if(!DECORATED.containsKey(v)){DECORATED.put(v,true);if(v instanceof Button)decorateButton((Button)v,primary);else if(v instanceof Spinner)decorateSpinner((Spinner)v,primary);else if(v instanceof CompoundButton)decorateCompound((CompoundButton)v,primary);else if(v instanceof EditText)decorateEdit((EditText)v,dark);else if(v instanceof TextView)decorateText((TextView)v);if((v instanceof Button)||(v instanceof Spinner)||(v instanceof Switch)||(v instanceof CheckBox)||((v instanceof ViewGroup)&&v.isClickable()))attachTouch(v);}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)decorateTree(g.getChildAt(i),primary,dark);}}
    private static void decorateButton(Button b,int primary){b.setAllCaps(false);b.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));b.setLetterSpacing(.005f);b.setMinHeight(dp(b.getContext(),48));b.setSoundEffectsEnabled(false);b.setStateListAnimator(null);Drawable d=b.getBackground();if(d!=null&&!(d instanceof RippleDrawable))try{b.setBackground(new RippleDrawable(ColorStateList.valueOf(alpha(V4Theme.coral(),42)),d,null));}catch(Exception ignored){}}
    private static void decorateSpinner(Spinner s,int primary){s.setSoundEffectsEnabled(false);s.setMinimumHeight(dp(s.getContext(),48));try{s.setElevation(0f);}catch(Exception ignored){}}
    private static void decorateCompound(CompoundButton c,int primary){c.setSoundEffectsEnabled(false);c.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));c.setMinHeight(dp(c.getContext(),46));}
    private static void decorateEdit(EditText e,boolean dark){e.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));e.setHintTextColor(dark?Color.rgb(149,185,174):Color.rgb(119,145,137));e.setLineSpacing(0f,1.08f);}
    private static void decorateText(TextView t){t.setIncludeFontPadding(false);t.setLineSpacing(0f,1.04f);}
    private static void attachTouch(View v){v.setOnTouchListener((view,event)->{int a=event.getActionMasked();if(a==MotionEvent.ACTION_DOWN&&UiFeedback.motionEnabled(view.getContext()))view.animate().scaleX(.976f).scaleY(.976f).alpha(.94f).setDuration(55).start();else if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_CANCEL){if(UiFeedback.motionEnabled(view.getContext()))view.animate().scaleX(1f).scaleY(1f).alpha(1f).setInterpolator(new OvershootInterpolator(1.12f)).setDuration(150).start();if(a==MotionEvent.ACTION_UP){if("preview_feedback".equals(view.getTag()))UiFeedback.preview(view);else UiFeedback.click(view);}}return false;});}
    public static int alpha(int color,int a){return Color.argb(Math.max(0,Math.min(255,a)),Color.red(color),Color.green(color),Color.blue(color));}private static int dp(Context c,int n){return(int)(n*c.getResources().getDisplayMetrics().density+.5f);}private ModernUi(){}
}
''',encoding='utf-8')

# Ensure the responsive shell requests safe insets immediately after setContentView as well as via lifecycle polish.
main=Path('app/src/main/java/com/rafat/munasabati/MainActivity.java')
s=main.read_text(encoding='utf-8')
s=s.replace('addBottomNavigation(root);setContentView(root);showSkeleton();','addBottomNavigation(root);setContentView(root);ModernUi.installSafeArea(this);showSkeleton();')
main.write_text(s,encoding='utf-8')
print('v4.5.2 system safe-area / Android 15 insets applied')
