package com.rafat.munasabati;

import android.app.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

public class AhlBaytCenterActivity extends Activity{
 private int primary;private LinearLayout root;private boolean ar(){return AppSettings.isArabic(this);}private String tr(String a,String e){return AppSettings.tr(this,a,e);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 @Override public void onCreate(Bundle b){super.onCreate(b);V4Theme.apply(this);primary=V4Theme.primary(this);render();}
 private void render(){ScrollView s=new ScrollView(this);s.setBackgroundColor(ModernUi.screenBackground(this));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(14),dp(16),dp(26));root.setLayoutDirection(ar()?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);s.addView(root);LinearLayout hero=card(primary);TextView h=t(tr("تقويم أهل البيت عليهم السلام","Ahl al-Bayt Calendar"),26,true);h.setTextColor(Color.WHITE);hero.addView(h);TextView sub=t(tr("مواليد ووفيات واستشهادات المعصومين الأربعة عشر بتقويم هجري متجدد.","Birth, death and martyrdom anniversaries of the Fourteen Infallibles in a recurring Hijri calendar."),12,false);sub.setTextColor(Color.rgb(225,239,236));hero.addView(sub);List<AhlBaytCalendar.Occurrence> next=AhlBaytCalendar.next(this,12);if(!next.isEmpty()){AhlBaytCalendar.Occurrence n=next.get(0);TextView nearest=t("\n"+AhlBaytCalendar.icon(n.occasion)+"  "+tr("المناسبة القادمة","Next occasion")+"\n"+AhlBaytCalendar.title(this,n.occasion)+"\n"+DateTools.hijri(this,n.time)+"  •  "+DateTools.gregorianShort(this,n.time),16,true);nearest.setTextColor(Color.WHITE);hero.addView(nearest);}LinearLayout options=card(ModernUi.surface(this));Switch births=sw(tr("✦ إظهار المواليد","✦ Show births"),AhlBaytCalendar.showBirths(this));Switch deaths=sw(tr("🕯 إظهار الوفيات والاستشهادات","🕯 Show deaths & martyrdoms"),AhlBaytCalendar.showDeaths(this));Switch alt=sw(tr("اعتماد الرواية البديلة حيث تم تحديد تاريخ بديل صريح","Prefer alternate narration where an explicit alternate date is defined"),AhlBaytCalendar.preferAlternate(this));Switch reminders=sw(tr("🔔 ذكرني بهذه المناسبات الساعة 8 صباحًا","🔔 Remind me of these occasions at 8:00 AM"),AhlBaytCalendar.remindersEnabled(this));options.addView(births);options.addView(deaths);options.addView(alt);options.addView(reminders);births.setOnCheckedChangeListener((b1,v)->{AhlBaytCalendar.setShowBirths(this,v);render();});deaths.setOnCheckedChangeListener((b1,v)->{AhlBaytCalendar.setShowDeaths(this,v);render();});alt.setOnCheckedChangeListener((b1,v)->{AhlBaytCalendar.setPreferAlternate(this,v);AhlBaytReminderScheduler.schedule(this);render();});reminders.setOnCheckedChangeListener((b1,v)->AhlBaytCalendar.setRemindersEnabled(this,v));TextView note=t(tr("الرواية البديلة تغيّر فقط المناسبات التي لديها تاريخ بديل محدد بوضوح داخل قاعدة التطبيق؛ بقية الاختلافات تبقى كملاحظة تاريخية.","Alternate narration changes only occasions with an explicit alternate date in the app database; other historical variants remain notes."),11,false);note.setTextColor(ModernUi.muted(this));note.setPadding(0,dp(8),0,0);options.addView(note);TextView timeline=t(tr("المناسبات القادمة","Upcoming timeline"),18,true);timeline.setTextColor(ModernUi.ink(this));timeline.setPadding(dp(2),dp(2),dp(2),dp(8));root.addView(timeline);for(AhlBaytCalendar.Occurrence o:next)addOccasion(o);setContentView(s);}
 private void addOccasion(AhlBaytCalendar.Occurrence o){LinearLayout c=card(ModernUi.surface(this));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);c.addView(row);TextView icon=t(AhlBaytCalendar.icon(o.occasion),25,false);icon.setGravity(Gravity.CENTER);icon.setTextColor(AhlBaytCalendar.color(o.occasion));row.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout txt=new LinearLayout(this);txt.setOrientation(LinearLayout.VERTICAL);row.addView(txt,new LinearLayout.LayoutParams(0,-2,1));TextView name=t(AhlBaytCalendar.title(this,o.occasion),15,true);name.setTextColor(ModernUi.ink(this));txt.addView(name);TextView date=t(DateTools.hijri(this,o.time)+"  •  "+DateTools.gregorianShort(this,o.time),12,false);date.setTextColor(ModernUi.muted(this));txt.addView(date);String note=AhlBaytCalendar.note(this,o.occasion);if(!note.isEmpty()){TextView n=t("ⓘ "+note,11,false);n.setTextColor(ModernUi.muted(this));n.setPadding(0,dp(5),0,0);c.addView(n);}}
 private LinearLayout card(int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(15));c.setBackground(bg(color,22));c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));root.addView(c,p);return c;}private Switch sw(String x,boolean v){Switch s=new Switch(this);s.setText(x);s.setTextSize(14);s.setTextColor(ModernUi.ink(this));s.setChecked(v);s.setMinHeight(dp(50));return s;}private TextView t(String x,int z,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);if(b)v.setTypeface(null,1);return v;}
}
