package com.rafat.munasabati;

import android.content.Context;

/** Concise respectful profile text used by the dedicated calendar UI. */
public final class AhlBaytProfiles{
 public static String badge(AhlBaytCalendar.Occasion o){String s=o.ar;if(s.contains("النبي محمد"))return"ﷺ";if(s.contains("فاطمة الزهراء"))return"ف";if(s.contains("علي أمير"))return"١";if(s.contains("الحسن المجتبى"))return"٢";if(s.contains("الحسين سيد"))return"٣";if(s.contains("زين العابدين"))return"٤";if(s.contains("محمد الباقر"))return"٥";if(s.contains("جعفر الصادق"))return"٦";if(s.contains("موسى الكاظم"))return"٧";if(s.contains("علي الرضا"))return"٨";if(s.contains("محمد الجواد"))return"٩";if(s.contains("علي الهادي"))return"١٠";if(s.contains("الحسن العسكري"))return"١١";if(s.contains("محمد المهدي"))return"١٢";return AhlBaytCalendar.icon(o);}
 public static String bio(Context c,AhlBaytCalendar.Occasion o){boolean ar=AppSettings.isArabic(c);String s=o.ar;if(s.contains("النبي محمد"))return ar?"خاتم الأنبياء ورسول الإسلام ﷺ، وجدّ الأئمة من أهل البيت عليهم السلام.":"The final Prophet and Messenger of Islam, and grandfather of the Imams of Ahl al-Bayt.";if(s.contains("فاطمة الزهراء"))return ar?"سيدة نساء العالمين، ابنة النبي محمد ﷺ وأم الأئمة من ذريتها عليهم السلام.":"Daughter of Prophet Muhammad, revered as the Lady of the Women of the Worlds and mother of the Imams through her lineage.";if(s.contains("علي أمير"))return ar?"أمير المؤمنين وأول أئمة أهل البيت عليهم السلام.":"Commander of the Faithful and the first Imam of Ahl al-Bayt.";if(s.contains("الحسن المجتبى"))return ar?"الإمام الثاني وسبط النبي الأكبر عليه السلام.":"The second Imam and elder grandson of the Prophet.";if(s.contains("الحسين سيد"))return ar?"الإمام الثالث وسيد الشهداء، ارتبطت شهادته بواقعة عاشوراء.":"The third Imam and Master of Martyrs, whose martyrdom is commemorated on Ashura.";if(s.contains("زين العابدين"))return ar?"الإمام الرابع، اشتهر بالعبادة والصحيفة السجادية.":"The fourth Imam, renowned for worship and the supplications of al-Sahifa al-Sajjadiyya.";if(s.contains("محمد الباقر"))return ar?"الإمام الخامس، عُرف ببقر العلوم ونشر معارف أهل البيت.":"The fifth Imam, known for expanding and transmitting the teachings of Ahl al-Bayt.";if(s.contains("جعفر الصادق"))return ar?"الإمام السادس، ارتبط باسمه تراث فقهي وعلمي واسع.":"The sixth Imam, associated with an extensive juristic and scholarly legacy.";if(s.contains("موسى الكاظم"))return ar?"الإمام السابع، عُرف بالصبر وكظم الغيظ.":"The seventh Imam, remembered for patience and restraint.";if(s.contains("علي الرضا"))return ar?"الإمام الثامن، مرقده الشريف في مشهد.":"The eighth Imam, whose shrine is in Mashhad.";if(s.contains("محمد الجواد"))return ar?"الإمام التاسع، تولّى الإمامة في سن مبكرة.":"The ninth Imam, who assumed the Imamate at a young age.";if(s.contains("علي الهادي"))return ar?"الإمام العاشر، عاش جانبًا من حياته في سامراء.":"The tenth Imam, who spent part of his life in Samarra.";if(s.contains("الحسن العسكري"))return ar?"الإمام الحادي عشر ووالد الإمام المهدي عجل الله فرجه الشريف.":"The eleventh Imam and father of Imam al-Mahdi.";if(s.contains("محمد المهدي"))return ar?"الإمام الثاني عشر، المهدي المنتظر عجل الله فرجه الشريف.":"The twelfth Imam, al-Mahdi, whose reappearance is awaited.";return"";}
 private AhlBaytProfiles(){}
}
