package com.rafat.munasabati;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;

public class AlertDiagnosticsActivity extends Activity{
 private int primary;private LinearLayout root;private boolean ar(){return AppSettings.isArabic(this);}private String tr(String a,String e){return AppSettings.tr(this,a,e);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 @Override public void onCreate(Bundle b){super.onCreate(b);V4Theme.apply(this);primary=V4Theme.primary(this);build();}
 private void build(){ScrollView s=new ScrollView(this);s.setBackgroundColor(ModernUi.screenBackground(this));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(14),dp(16),dp(26));root.setLayoutDirection(ar()?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);s.addView(root);LinearLayout hero=card(primary);TextView h=t(tr("التنبيهات وStrong Alert","Alerts & Strong Alert"),26,true);h.setTextColor(Color.WHITE);hero.addView(h);TextView sub=t(tr("اختبر كل طبقة من نظام التنبيه وتأكد من الصلاحيات.","Test each alert layer and verify permissions."),12,false);sub.setTextColor(Color.rgb(225,239,236));hero.addView(sub);LinearLayout health=card(ModernUi.surface(this));boolean notif=Build.VERSION.SDK_INT<33||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED;boolean fs=StrongAlertSupport.canUseFullScreen(this);AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);boolean exact=Build.VERSION.SDK_INT<31||am.canScheduleExactAlarms();PowerManager pm=(PowerManager)getSystemService(POWER_SERVICE);boolean battery=pm.isIgnoringBatteryOptimizations(getPackageName());status(health,notif,tr("الإشعارات مسموحة","Notifications allowed"));status(health,fs,tr("Strong Alert يمكنه استخدام Full Screen","Strong Alert full-screen access"));status(health,exact,tr("التنبيهات الدقيقة مسموحة","Exact alarms allowed"));status(health,battery,tr("قيود البطارية لا تمنع الخلفية","Battery optimization exemption"));Button test=b(tr("🔔 اختبار إشعار عادي الآن","🔔 Test regular notification"),primary,Color.WHITE);health.addView(test,p(-1,dp(50),0,dp(12),0,0));test.setOnClickListener(v->testNormal());Button strong=b(tr("⚠ اختبار شاشة Strong Alert","⚠ Test Strong Alert screen"),ModernUi.surface(this),primary);health.addView(strong,p(-1,dp(50),0,dp(7),0,0));strong.setOnClickListener(v->startActivity(new Intent(this,StrongAlertActivity.class).putExtra("event_id",0L).putExtra("occurrence_time",System.currentTimeMillis())));Button settingsBtn=b(tr("فتح إعدادات Strong Alert","Open Strong Alert settings"),ModernUi.surface(this),primary);health.addView(settingsBtn,p(-1,dp(48),0,dp(7),0,0));settingsBtn.setOnClickListener(v->StrongAlertSupport.openFullScreenSettings(this));TextView note=t(tr("الملف العادي = إشعار تقليدي. المهم = Strong Alert عند أقرب تذكير. العاجل = Strong Alert لكل تذكير محدد.","Normal = regular notification. Important = Strong Alert at the closest reminder. Urgent = Strong Alert for every selected reminder."),12,false);note.setTextColor(ModernUi.muted(this));note.setPadding(0,dp(10),0,0);health.addView(note);setContentView(s);}
 private void testNormal(){NotificationSupport.ensureChannel(this);NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,NotificationSupport.CHANNEL_ID):new Notification.Builder(this);b.setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle(tr("اختبار مناسبـاتي","Munasabati test")).setContentText(tr("إذا رأيت وسمعت هذا الإشعار فالقناة العادية تعمل.","If you can see and hear this, the regular notification channel works.")).setAutoCancel(true).setPriority(Notification.PRIORITY_MAX).setDefaults(Notification.DEFAULT_ALL);nm.notify(43043,b.build());}
 private LinearLayout card(int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(17),dp(15),dp(17),dp(16));c.setBackground(bg(color,24));c.setElevation(dp(2));root.addView(c,p(-1,-2,0,0,0,dp(12)));return c;}private void status(LinearLayout c,boolean ok,String x){TextView t=t((ok?"✅ ":"⚠️ ")+x,14,true);t.setTextColor(ok?primary:Color.rgb(173,92,35));t.setPadding(0,dp(5),0,dp(5));c.addView(t);}private Button b(String x,int back,int text){Button v=new Button(this);v.setAllCaps(false);v.setText(x);v.setTextColor(text);v.setTextSize(14);v.setBackground(bg(back,15));return v;}private TextView t(String x,int z,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);if(b)v.setTypeface(null,1);return v;}private LinearLayout.LayoutParams p(int w,int h,int l,int tt,int r,int bb){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(l,tt,r,bb);return p;}
}
