package com.rafat.munasabati;
import android.app.*;import android.appwidget.*;import android.content.*;import android.widget.RemoteViews;import java.text.*;import java.util.*;
public final class ExtraWidgetUpdater{
 static EventStore.Event nearest(Context c){long now=System.currentTimeMillis(),best=Long.MAX_VALUE;EventStore.Event pick=null;for(EventStore.Event e:EventStore.load(c)){long t=Recurrence.isRecurring(e)?Recurrence.nextOccurrence(e,now):e.eventTime;if(t>=now&&t<best){best=t;pick=e;}}return pick;}static long time(EventStore.Event e){return e==null?0:(Recurrence.isRecurring(e)?Recurrence.nextOccurrence(e,System.currentTimeMillis()):e.eventTime);}static String rel(Context c,long t){long d=t-System.currentTimeMillis();if(d<=60000)return AppSettings.tr(c,"الآن","Now");if(d<3600000)return AppSettings.tr(c,"بعد ","in ")+Math.max(1,d/60000)+AppSettings.tr(c," دقيقة"," min");if(d<86400000)return AppSettings.tr(c,"بعد ","in ")+Math.max(1,d/3600000)+AppSettings.tr(c," ساعة"," hr");long n=Math.max(1,(long)Math.ceil(d/86400000.0));return AppSettings.isArabic(c)?(n==1?"متبقي يوم":n==2?"متبقي يومان":"متبقي "+n+" أيام"):(n==1?"1 day left":n+" days left");}
 static String title(Context c,EventStore.Event e){return V43Prefs.hideWidgetTitles(c)?V43Prefs.privateTitle(c):Categories.icon(e.category)+"  "+e.title;}
 public static void mini(Context c,AppWidgetManager m,int id){RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_mini);EventStore.Event e=nearest(c);if(e==null){v.setTextViewText(R.id.mini_title,AppSettings.tr(c,"لا توجد مناسبات قادمة","No upcoming events"));v.setTextViewText(R.id.mini_count,"");}else{long t=time(e);v.setTextViewText(R.id.mini_title,title(c,e));v.setTextViewText(R.id.mini_count,rel(c,t));Intent o=new Intent(c,LauncherActivity.class).putExtra("event_id",e.id);v.setOnClickPendingIntent(R.id.mini_root,PendingIntent.getActivity(c,6100+id,o,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));}m.updateAppWidget(id,v);stamp(c);}
 public static void countdown(Context c,AppWidgetManager m,int id){RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_countdown);EventStore.Event e=nearest(c);if(e==null){v.setTextViewText(R.id.count_title,AppSettings.tr(c,"لا توجد مناسبة قادمة","No upcoming event"));v.setTextViewText(R.id.count_big,"—");v.setTextViewText(R.id.count_date,"");}else{long t=time(e);v.setTextViewText(R.id.count_title,title(c,e));v.setTextViewText(R.id.count_big,rel(c,t));v.setTextViewText(R.id.count_date,DateTools.gregorianShort(c,t)+" • "+DateTools.time(c,t));Intent o=new Intent(c,LauncherActivity.class).putExtra("event_id",e.id);v.setOnClickPendingIntent(R.id.count_root,PendingIntent.getActivity(c,6200+id,o,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));}m.updateAppWidget(id,v);stamp(c);}
 public static void month(Context c,AppWidgetManager m,int id){RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_month);Calendar x=Calendar.getInstance();v.setTextViewText(R.id.month_title,new SimpleDateFormat("MMMM yyyy",AppSettings.isArabic(c)?new Locale("ar"):Locale.ENGLISH).format(x.getTime()));Calendar first=(Calendar)x.clone();first.set(Calendar.DAY_OF_MONTH,1);int off=first.get(Calendar.DAY_OF_WEEK)-1,max=first.getActualMaximum(Calendar.DAY_OF_MONTH);StringBuilder b=new StringBuilder(AppSettings.isArabic(c)?"أح  إث  ثل  أر  خم  جم  سب\n":"Su  Mo  Tu  We  Th  Fr  Sa\n");for(int i=0;i<off;i++)b.append("    ");for(int d=1;d<=max;d++){b.append(String.format(Locale.US,"%2d  ",d));if((off+d)%7==0)b.append("\n");}v.setTextViewText(R.id.month_grid,b.toString());Intent o=new Intent(c,LauncherActivity.class);v.setOnClickPendingIntent(R.id.month_root,PendingIntent.getActivity(c,6300+id,o,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));m.updateAppWidget(id,v);stamp(c);}
 public static void updateAll(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);for(int id:m.getAppWidgetIds(new ComponentName(c,MiniWidgetProvider.class)))mini(c,m,id);for(int id:m.getAppWidgetIds(new ComponentName(c,CountdownWidgetProvider.class)))countdown(c,m,id);for(int id:m.getAppWidgetIds(new ComponentName(c,MonthWidgetProvider.class)))month(c,m,id);}
 static void stamp(Context c){c.getSharedPreferences("munasabati_v4",0).edit().putLong("widget_last_update",System.currentTimeMillis()).apply();}private ExtraWidgetUpdater(){}
}
