package com.rafat.munasabati;
import android.app.*;import android.os.Bundle;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import org.json.*;
public class GuestManagerActivity extends Activity{
 long id;V4Meta.Meta meta;LinearLayout list;EditText name;Spinner status;int primary=Color.rgb(25,91,86);boolean ar(){return AppSettings.isArabic(this);}String tr(String a,String e){return AppSettings.tr(this,a,e);}int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 @Override public void onCreate(Bundle b){super.onCreate(b);id=getIntent().getLongExtra("event_id",0);meta=V4Meta.get(this,id);ScrollView s=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(14),dp(16),dp(24));s.addView(r);TextView h=t(tr("دعوات وحالة الحضور","Invitations & attendance"),25,true);h.setTextColor(primary);r.addView(h);name=new EditText(this);name.setHint(tr("اسم المدعو","Guest name"));r.addView(name,new LinearLayout.LayoutParams(-1,dp(52)));status=new Spinner(this);status.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ar()?new String[]{"مدعو","أكد الحضور","اعتذر","لم يرد"}:new String[]{"Invited","Confirmed","Declined","No response"}));r.addView(status,new LinearLayout.LayoutParams(-1,dp(52)));Button add=new Button(this);add.setText(tr("＋ إضافة المدعو","＋ Add guest"));r.addView(add,new LinearLayout.LayoutParams(-1,dp(52)));add.setOnClickListener(v->addGuest());list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);setContentView(s);render();}
 void addGuest(){String n=name.getText().toString().trim();if(n.isEmpty())return;try{JSONArray a=V4Meta.guests(meta);JSONObject o=new JSONObject();o.put("name",n);o.put("status",new String[]{"invited","yes","no","pending"}[status.getSelectedItemPosition()]);a.put(o);meta.guestsJson=a.toString();V4Meta.put(this,id,meta);name.setText("");render();V4Log.history(this,id,"guests","Guest added: "+n);}catch(Exception ignored){}}
 void render(){list.removeAllViews();int[] c=V4Meta.guestCounts(meta);TextView sum=t((ar()?"✓ ":"")+c[0]+tr(" مؤكد / "," confirmed / ")+c[1]+tr(" معتذر / "," declined / ")+c[2]+tr(" بانتظار الرد"," pending"),15,true);sum.setTextColor(primary);sum.setPadding(0,dp(12),0,dp(8));list.addView(sum);JSONArray a=V4Meta.guests(meta);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;final int idx=i;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(12),dp(8),dp(12),dp(8));row.setBackground(bg(Color.WHITE,14));TextView txt=t(o.optString("name")+"  •  "+statusLabel(o.optString("status")),14,true);row.addView(txt,new LinearLayout.LayoutParams(0,dp(42),1));Button del=new Button(this);del.setText("×");row.addView(del,new LinearLayout.LayoutParams(dp(46),dp(42)));del.setOnClickListener(v->remove(idx));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(6));list.addView(row,p);}}
 void remove(int idx){JSONArray a=V4Meta.guests(meta),b=new JSONArray();for(int i=0;i<a.length();i++)if(i!=idx)b.put(a.opt(i));meta.guestsJson=b.toString();V4Meta.put(this,id,meta);render();}
 String statusLabel(String s){if("yes".equals(s))return tr("أكد الحضور","Confirmed");if("no".equals(s))return tr("اعتذر","Declined");if("pending".equals(s))return tr("لم يرد","No response");return tr("مدعو","Invited");}
 TextView t(String x,int z,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);if(b)v.setTypeface(null,1);return v;}
}
