package com.rafat.munasabati;
import android.app.*;import android.content.*;import android.graphics.Color;import android.hardware.biometrics.BiometricPrompt;import android.os.*;import android.view.*;import android.widget.*;import java.security.MessageDigest;import java.util.concurrent.Executor;
public class LauncherActivity extends Activity{
 private static final String P="munasabati_v4";boolean done=false;String tr(String a,String e){return AppSettings.tr(this,a,e);} @Override public void onCreate(Bundle b){super.onCreate(b);V4Theme.apply(this);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(40,40,40,40);TextView t=new TextView(this);t.setText("🔐\n"+tr("مناسباتي","Munasabati"));t.setGravity(Gravity.CENTER);t.setTextSize(28);t.setTextColor(V4Theme.primary(this));r.addView(t);setContentView(r);if(!getSharedPreferences(P,0).getBoolean("lock_enabled",false)){open();return;}new Handler(Looper.getMainLooper()).postDelayed(this::unlock,180);}
 private void unlock(){if(Build.VERSION.SDK_INT>=28){try{Executor ex=getMainExecutor();BiometricPrompt p=new BiometricPrompt.Builder(this).setTitle(tr("فتح مناسبـاتي","Unlock Munasabati")).setSubtitle(tr("استخدم البصمة أو الوجه","Use fingerprint or face")).setNegativeButton(tr("استخدام PIN","Use PIN"),ex,(d,w)->pin()).build();p.authenticate(new CancellationSignal(),ex,new BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){open();}@Override public void onAuthenticationError(int c,CharSequence m){if(!done)pin();}});return;}catch(Exception ignored){}}pin();}
 private void pin(){final EditText e=new EditText(this);e.setInputType(2);e.setHint("PIN");new AlertDialog.Builder(this).setTitle(tr("أدخل رمز PIN","Enter PIN")).setView(e).setCancelable(false).setNegativeButton(tr("إغلاق","Close"),(d,w)->finish()).setPositiveButton(tr("فتح","Unlock"),null).setOnShowListener(d->{AlertDialog a=(AlertDialog)d;a.getButton(-1).setOnClickListener(v->{String h=getSharedPreferences(P,0).getString("pin_hash","");if(h.equals(hash(e.getText().toString())))open();else{e.setError(tr("رمز غير صحيح","Incorrect PIN"));e.setText("");}});}).show();}
 private void open(){if(done)return;done=true;Intent src=getIntent();long eventId=src.getLongExtra("event_id",0);boolean templates=src.getBooleanExtra("open_templates",false);startActivity(new Intent(this,MainActivity.class));if(eventId>0)startActivity(new Intent(this,EditEventActivity.class).putExtra("event_id",eventId));else if(templates)startActivity(new Intent(this,TemplateChooserActivity.class));finish();}
 public static String hash(String s){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes("UTF-8"));StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();}catch(Exception e){return s;}}
}
