package com.rafat.munasabati;

import android.app.Activity;import android.content.Context;import android.content.res.ColorStateList;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.*;import android.os.Build;import android.view.*;import android.view.animation.OvershootInterpolator;import android.widget.*;import java.util.WeakHashMap;

/** Native, dependency-free Material-3-inspired polish for all programmatic screens. */
public final class ModernUi {
    private static final WeakHashMap<View,Boolean> DECORATED=new WeakHashMap<>();private static final WeakHashMap<Activity,Boolean> ANIMATED=new WeakHashMap<>();
    public static void apply(Activity a){if(a==null||a instanceof StrongAlertActivity)return;boolean dark=isDark(a);int primary=V4Theme.primary(a);Window w=a.getWindow();try{w.setStatusBarColor(primary);w.setNavigationBarColor(dark?Color.rgb(18,24,27):Color.rgb(247,249,250));if(Build.VERSION.SDK_INT>=26){int f=w.getDecorView().getSystemUiVisibility();if(dark)f&=~View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;else f|=View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;w.getDecorView().setSystemUiVisibility(f);}}catch(Exception ignored){}View root=w.getDecorView().findViewById(android.R.id.content);if(root==null)root=w.getDecorView();decorateTree(root,primary,dark);if(UiFeedback.motionEnabled(a)&&!ANIMATED.containsKey(a)){ANIMATED.put(a,true);root.setAlpha(0f);root.setTranslationY(dp(a,8));root.animate().alpha(1f).translationY(0f).setDuration(220).start();}}
    public static void modernCard(View v){if(v==null)return;try{v.setElevation(dp(v.getContext(),2));v.setClipToOutline(false);}catch(Exception ignored){}}public static GradientDrawable fieldBackground(Context c,int primary){GradientDrawable g=new GradientDrawable();g.setColor(isDark(c)?Color.rgb(31,39,43):Color.rgb(249,250,251));g.setCornerRadius(dp(c,15));g.setStroke(dp(c,1),alpha(primary,isDark(c)?100:52));return g;}public static int screenBackground(Context c){return isDark(c)?Color.rgb(18,24,27):Color.rgb(247,249,250);}public static int surface(Context c){return isDark(c)?Color.rgb(28,35,39):Color.WHITE;}public static int ink(Context c){return isDark(c)?Color.rgb(239,244,246):Color.rgb(29,38,49);}public static int muted(Context c){return isDark(c)?Color.rgb(177,189,194):Color.rgb(92,103,115);}public static boolean isDark(Context c){return (c.getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)==android.content.res.Configuration.UI_MODE_NIGHT_YES;}
    private static void decorateTree(View v,int primary,boolean dark){if(v==null)return;if(!DECORATED.containsKey(v)){DECORATED.put(v,true);if(v instanceof Button)decorateButton((Button)v,primary);else if(v instanceof Spinner)decorateSpinner((Spinner)v,primary);else if(v instanceof CompoundButton)decorateCompound((CompoundButton)v,primary);else if(v instanceof EditText)decorateEdit((EditText)v,dark);else if(v instanceof TextView)decorateText((TextView)v);if((v instanceof Button)||(v instanceof Spinner)||(v instanceof Switch)||(v instanceof CheckBox)||((v instanceof ViewGroup)&&v.isClickable()))attachTouch(v);}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)decorateTree(g.getChildAt(i),primary,dark);}}
    private static void decorateButton(Button b,int primary){b.setAllCaps(false);b.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));b.setLetterSpacing(.01f);b.setMinHeight(dp(b.getContext(),48));b.setSoundEffectsEnabled(false);b.setStateListAnimator(null);Drawable d=b.getBackground();if(d!=null&&!(d instanceof RippleDrawable))try{b.setBackground(new RippleDrawable(ColorStateList.valueOf(alpha(primary,36)),d,null));}catch(Exception ignored){}}
    private static void decorateSpinner(Spinner s,int primary){s.setSoundEffectsEnabled(false);s.setMinimumHeight(dp(s.getContext(),48));try{s.setElevation(0f);}catch(Exception ignored){}}private static void decorateCompound(CompoundButton c,int primary){c.setSoundEffectsEnabled(false);c.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));c.setMinHeight(dp(c.getContext(),46));}private static void decorateEdit(EditText e,boolean dark){e.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));e.setHintTextColor(dark?Color.rgb(139,151,157):Color.rgb(139,148,158));e.setLineSpacing(0f,1.08f);}private static void decorateText(TextView t){t.setIncludeFontPadding(false);t.setLineSpacing(0f,1.04f);}
    private static void attachTouch(View v){v.setOnTouchListener((view,event)->{int a=event.getActionMasked();if(a==MotionEvent.ACTION_DOWN&&UiFeedback.motionEnabled(view.getContext()))view.animate().scaleX(.976f).scaleY(.976f).alpha(.94f).setDuration(55).start();else if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_CANCEL){if(UiFeedback.motionEnabled(view.getContext()))view.animate().scaleX(1f).scaleY(1f).alpha(1f).setInterpolator(new OvershootInterpolator(1.15f)).setDuration(155).start();if(a==MotionEvent.ACTION_UP){if("preview_feedback".equals(view.getTag()))UiFeedback.preview(view);else UiFeedback.click(view);}}return false;});}
    public static int alpha(int color,int a){return Color.argb(Math.max(0,Math.min(255,a)),Color.red(color),Color.green(color),Color.blue(color));}private static int dp(Context c,int n){return(int)(n*c.getResources().getDisplayMetrics().density+.5f);}private ModernUi(){}
}
