package com.rafat.munasabati;

import android.app.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;

public class PrivacySettingsActivity extends Activity{
 private int primary;private boolean ar(){return AppSettings.isArabic(this);}private String tr(String a,String e){return AppSettings.tr(this,a,e);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 @Override public void onCreate(Bundle b){super.onCreate(b);V4Theme.apply(this);primary=V4Theme.primary(this);ScrollView s=new ScrollView(this);s.setBackgroundColor(ModernUi.screenBackground(this));LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(14),dp(16),dp(26));root.setLayoutDirection(ar()?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);s.addView(root);LinearLayout hero=card(root,primary);TextView h=t(tr("الخصوصية والقفل","Privacy & lock"),26,true);h.setTextColor(Color.WHITE);hero.addView(h);TextView sub=t(tr("تحكم بما يظهر على الشاشة والإشعارات ومدة القفل التلقائي.","Control what appears on screen, notifications and auto-lock timing."),12,false);sub.setTextColor(Color.rgb(224,239,236));hero.addView(sub);LinearLayout c=card(root,ModernUi.surface(this));TextView l=t(tr("القفل التلقائي","Auto-lock"),15,true);l.setTextColor(ModernUi.ink(this));c.addView(l);Spinner lock=new Spinner(this);String[] labels=ar()?new String[]{"فورًا","30 ثانية","دقيقة","5 دقائق","15 دقيقة"}:new String[]{"Immediately","30 seconds","1 minute","5 minutes","15 minutes"};long[] vals={0,30000,60000,300000,900000};lock.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));long cur=V43Prefs.autoLockMs(this);int sel=2;for(int i=0;i<vals.length;i++)if(vals[i]==cur)sel=i;lock.setSelection(sel);c.addView(lock,new LinearLayout.LayoutParams(-1,dp(52)));lock.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){boolean first=true;public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(first){first=false;return;}V43Prefs.setAutoLockMs(PrivacySettingsActivity.this,vals[pos]);}public void onNothingSelected(AdapterView<?>p){}});Switch notif=sw(tr("إخفاء تفاصيل المناسبات من الإشعارات","Hide event details in notifications"),V43Prefs.hideNotificationContent(this));c.addView(notif);notif.setOnCheckedChangeListener((b1,v)->V43Prefs.setHideNotificationContent(this,v));Switch widget=sw(tr("إخفاء أسماء المناسبات من Widgets","Hide event names in widgets"),V43Prefs.hideWidgetTitles(this));c.addView(widget);widget.setOnCheckedChangeListener((b1,v)->V43Prefs.setHideWidgetTitles(this,v));Switch attach=sw(tr("طلب القفل قبل فتح المرفقات الحساسة","Require lock before sensitive attachments"),V43Prefs.protectAttachments(this));c.addView(attach);attach.setOnCheckedChangeListener((b1,v)->V43Prefs.setProtectAttachments(this,v));Switch exports=sw(tr("طلب القفل قبل التصدير أو المشاركة","Require lock before export / sharing"),V43Prefs.protectExports(this));c.addView(exports);exports.setOnCheckedChangeListener((b1,v)->V43Prefs.setProtectExports(this,v));TextView info=t(tr("البيانات الأساسية محفوظة محليًا. الأحداث التي تفعل لها Sync فقط تُرسل إلى التقويم الخارجي المحدد.","Core data stays local. Only events with Sync enabled are sent to the selected external calendar."),12,false);info.setTextColor(ModernUi.muted(this));info.setPadding(0,dp(10),0,0);c.addView(info);setContentView(s);}
 private LinearLayout card(LinearLayout root,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(17),dp(15),dp(17),dp(16));c.setBackground(bg(color,24));c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));root.addView(c,p);return c;}private Switch sw(String x,boolean on){Switch s=new Switch(this);s.setText(x);s.setTextSize(14);s.setTextColor(ModernUi.ink(this));s.setChecked(on);s.setMinHeight(dp(50));return s;}private TextView t(String x,int z,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);if(b)v.setTypeface(null,1);return v;}
}
