package com.rafat.munasabati;

import android.app.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public class SyncConflictActivity extends Activity{
 private int primary;private LinearLayout root;private boolean ar(){return AppSettings.isArabic(this);}private String tr(String a,String e){return AppSettings.tr(this,a,e);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 @Override public void onCreate(Bundle b){super.onCreate(b);V4Theme.apply(this);primary=V4Theme.primary(this);render();}
 private void render(){ScrollView s=new ScrollView(this);s.setBackgroundColor(ModernUi.screenBackground(this));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(14),dp(16),dp(26));root.setLayoutDirection(ar()?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);s.addView(root);LinearLayout hero=card(primary);TextView h=t(tr("حل تعارضات المزامنة","Resolve sync conflicts"),25,true);h.setTextColor(Color.WHITE);hero.addView(h);TextView sub=t(tr("لن يختار مناسبـاتي نسخة تلقائيًا عند تعديل الطرفين. قارن ثم قرر.","Munasabati no longer chooses automatically when both sides changed. Compare, then decide."),12,false);sub.setTextColor(Color.rgb(225,239,236));hero.addView(sub);JSONArray a=SyncConflictStore.list(this);if(a.length()==0){LinearLayout c=card(ModernUi.surface(this));TextView ok=t(tr("✅ لا توجد تعارضات معلقة.","✅ No pending conflicts."),16,true);ok.setTextColor(primary);c.addView(ok);}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)addConflict(i,o);}setContentView(s);}
 private void addConflict(int index,JSONObject o){LinearLayout c=card(ModernUi.surface(this));TextView name=t("⚠  "+o.optString("localTitle"),16,true);name.setTextColor(Color.rgb(166,92,28));c.addView(name);LinearLayout cols=new LinearLayout(this);cols.setPadding(0,dp(9),0,dp(9));c.addView(cols);cols.addView(snapshot(tr("نسخة مناسبـاتي","Munasabati"),o.optString("localTitle"),o.optLong("localStart"),o.optString("localLocation"),o.optString("localDetails"),primary),new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(0,-2,1);ep.setMargins(dp(7),0,0,0);cols.addView(snapshot(tr("نسخة Google/Outlook","Google/Outlook"),o.optString("externalTitle"),o.optLong("externalStart"),o.optString("externalLocation"),o.optString("externalDetails"),Color.rgb(67,99,170)),ep);LinearLayout actions=new LinearLayout(this);c.addView(actions);Button local=b(tr("اعتماد مناسبـاتي","Use Munasabati"),primary,Color.WHITE);Button external=b(tr("اعتماد التقويم الخارجي","Use external"),Color.rgb(67,99,170),Color.WHITE);actions.addView(local,new LinearLayout.LayoutParams(0,dp(52),1));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(52),1);xp.setMargins(dp(7),0,0,0);actions.addView(external,xp);local.setOnClickListener(v->{boolean ok=CalendarIntegration.forcePush(this,o.optLong("localId"));if(ok){SyncConflictStore.remove(this,index);Toast.makeText(this,tr("تم اعتماد نسخة مناسبـاتي","Munasabati version applied"),Toast.LENGTH_SHORT).show();render();}});external.setOnClickListener(v->{boolean ok=CalendarIntegration.resolveConflictUseExternal(this,o.optLong("localId"),o.optLong("externalId"));if(ok){SyncConflictStore.remove(this,index);Toast.makeText(this,tr("تم اعتماد النسخة الخارجية","External version applied"),Toast.LENGTH_SHORT).show();render();}});}
 private LinearLayout snapshot(String label,String title,long time,String loc,String details,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(10),dp(10),dp(10),dp(10));c.setBackground(bg(ModernUi.alpha(color,18),15));TextView h=t(label,12,true);h.setTextColor(color);c.addView(h);TextView n=t(title,13,true);n.setTextColor(ModernUi.ink(this));n.setPadding(0,dp(5),0,0);c.addView(n);String when=time<=0?"—":new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date(time));TextView m=t(when+(loc.isEmpty()?"":"\n📍 "+loc)+(details.isEmpty()?"":"\n"+details),11,false);m.setTextColor(ModernUi.muted(this));m.setMaxLines(5);m.setPadding(0,dp(4),0,0);c.addView(m);return c;}
 private LinearLayout card(int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(15));c.setBackground(bg(color,22));c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));root.addView(c,p);return c;}private Button b(String x,int back,int text){Button v=new Button(this);v.setAllCaps(false);v.setText(x);v.setTextColor(text);v.setTextSize(12);v.setBackground(bg(back,14));return v;}private TextView t(String x,int z,boolean b){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);if(b)v.setTypeface(null,1);return v;}
}
