package com.rafat.munasabati;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.*;import android.widget.*;

public class TemplateChooserActivity extends Activity{
 private int primary=Color.rgb(25,91,86);private LinearLayout root;private boolean ar(){return AppSettings.isArabic(this);}private String tr(String a,String e){return AppSettings.tr(this,a,e);}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(primary);ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.rgb(244,247,249));root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(24));root.setLayoutDirection(ar()?View.LAYOUT_DIRECTION_RTL:View.LAYOUT_DIRECTION_LTR);s.addView(root);TextView h=t(tr("اختر قالب المناسبة","Choose an event template"),27,true);h.setTextColor(primary);root.addView(h);TextView sub=t(tr("يمكنك البدء بقالب جاهز أو إنشاء مناسبة فارغة.","Start with a ready template or a blank event."),14,false);sub.setTextColor(Color.DKGRAY);sub.setPadding(0,dp(4),0,dp(14));root.addView(sub);add("＋",tr("مناسبة فارغة","Blank event"),"none","none","30");add("🎂",tr("عيد ميلاد","Birthday"),"birthday","yearly","10080,1440");add("💍",tr("زواج","Wedding"),"marriage","none","1440,180");add("✈",tr("سفر","Travel"),"travel","none","1440,180");add("💼",tr("اجتماع","Meeting"),"meeting","none","60,15");add("🌙",tr("عشاء","Dinner"),"dinner","none","180,60");add("🩺",tr("موعد طبي","Medical appointment"),"medical","none","1440,60");setContentView(s);}
 private void add(String icon,String name,String cat,String rec,String rem){Button b=new Button(this);b.setAllCaps(false);b.setText(icon+"   "+name);b.setTextSize(17);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setPadding(dp(18),0,dp(18),0);b.setTextColor(Color.rgb(31,42,55));b.setBackground(bg(Color.WHITE,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(62));p.setMargins(0,0,0,dp(9));root.addView(b,p);b.setOnClickListener(v->{Intent i=new Intent(this,EditEventActivity.class);i.putExtra("template_category",cat);i.putExtra("template_recurrence",rec);i.putExtra("template_reminders",rem);i.putExtra("template_name",name);startActivity(i);finish();});}
 private TextView t(String x,int s,boolean bold){TextView v=new TextView(this);v.setText(x);v.setTextSize(s);if(bold)v.setTypeface(null,1);return v;}
}
