package com.rafat.munasabati;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import java.util.*;

public final class V4EditorHooks{
 private static final WeakHashMap<Activity,State> STATES=new WeakHashMap<>();
 private static final class State{Spinner tag,tz,locType,radius;EditText web,phone,contact;CheckBox smart;TextView voice;String voiceUri="";long id;}
 private static int dp(Activity a,int n){return(int)(n*a.getResources().getDisplayMetrics().density+.5f);}private static String tr(Activity a,String ar,String en){return AppSettings.tr(a,ar,en);}private static GradientDrawable bg(Activity a,int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(a,r));return g;}
 public static void decorate(Activity a,LinearLayout root,long id,Spinner category,CheckBox[] checks,int[] values){State s=new State();s.id=id;V4Meta.Meta m=id>0?V4Meta.get(a,id):new V4Meta.Meta();s.voiceUri=m.voiceNoteUri;STATES.put(a,s);LinearLayout c=new LinearLayout(a);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(a,16),dp(a,14),dp(a,16),dp(a,15));c.setBackground(bg(a,Color.WHITE,21));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(a,10));root.addView(c,Math.max(0,root.getChildCount()-1),cp);TextView h=t(a,tr(a,"خيارات v4 الذكية","v4 smart options"),18,true);h.setTextColor(Color.rgb(25,91,86));c.addView(h);TextView sub=t(a,tr(a,"المجموعة، المنطقة الزمنية، التنبيهات الذكية، البيانات الإضافية وتذكير الموقع","Tags, time zone, smart reminders, extra contact data and location reminders"),12,false);sub.setTextColor(Color.DKGRAY);sub.setPadding(0,0,0,dp(a,8));c.addView(sub);
  s.tag=new Spinner(a);s.tag.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,V4Meta.tagLabels(a)));s.tag.setSelection(V4Meta.tagIndex(m.tag));c.addView(label(a,tr(a,"المجموعة / Tag","Group / Tag")));c.addView(s.tag,new LinearLayout.LayoutParams(-1,dp(a,50)));
  String[] zones={TimeZone.getDefault().getID(),"Asia/Riyadh","Europe/London","America/New_York","Asia/Dubai","Asia/Tokyo"};s.tz=new Spinner(a);s.tz.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,zones));int zi=0;for(int i=0;i<zones.length;i++)if(zones[i].equals(m.timeZoneId))zi=i;s.tz.setSelection(zi);c.addView(label(a,tr(a,"المنطقة الزمنية","Time zone")));c.addView(s.tz,new LinearLayout.LayoutParams(-1,dp(a,50)));
  s.smart=new CheckBox(a);s.smart.setText(tr(a,"استخدم التنبيهات الذكية لهذه الفئة","Use smart reminders for this category"));s.smart.setChecked(m.smartReminder);c.addView(s.smart);Button apply=new Button(a);apply.setAllCaps(false);apply.setText(tr(a,"✨ تطبيق Smart Reminder الآن","✨ Apply Smart Reminder now"));c.addView(apply,new LinearLayout.LayoutParams(-1,dp(a,48)));apply.setOnClickListener(v->applySmart(a,Categories.CODES[Math.max(0,category.getSelectedItemPosition())],checks,values));
  s.web=input(a,tr(a,"رابط ويب مرتبط بالمناسبة","Related web URL"),m.webUrl);s.phone=input(a,tr(a,"رقم هاتف","Phone number"),m.phone);s.contact=input(a,tr(a,"جهة اتصال / اسم شخص","Contact / person name"),m.contactName);c.addView(s.web,new LinearLayout.LayoutParams(-1,dp(a,50)));c.addView(s.phone,new LinearLayout.LayoutParams(-1,dp(a,50)));c.addView(s.contact,new LinearLayout.LayoutParams(-1,dp(a,50)));
  LinearLayout vr=new LinearLayout(a);vr.setGravity(Gravity.CENTER_VERTICAL);Button pickVoice=new Button(a);pickVoice.setAllCaps(false);pickVoice.setText(tr(a,"🎙 إرفاق ملاحظة صوتية","🎙 Attach voice note"));vr.addView(pickVoice,new LinearLayout.LayoutParams(0,dp(a,48),1));s.voice=t(a,m.voiceNoteUri.isEmpty()?tr(a,"لا توجد ملاحظة صوتية","No voice note"):tr(a,"✓ ملاحظة صوتية مرفقة","✓ Voice note attached"),11,false);vr.addView(s.voice,new LinearLayout.LayoutParams(0,dp(a,48),1));c.addView(vr);pickVoice.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("audio/*");a.startActivityForResult(i,9404);});
  c.addView(label(a,tr(a,"تذكير الموقع","Location reminder")));s.locType=new Spinner(a);s.locType.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,AppSettings.isArabic(a)?new String[]{"بدون","عند الوصول","عند المغادرة"}:new String[]{"None","On arrival","On leaving"}));s.locType.setSelection("arrive".equals(m.locationReminder)?1:("leave".equals(m.locationReminder)?2:0));c.addView(s.locType,new LinearLayout.LayoutParams(-1,dp(a,50)));s.radius=new Spinner(a);s.radius.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"100 m","250 m","500 m","1000 m"}));float[] rv={100,250,500,1000};int ri=1;for(int i=0;i<rv.length;i++)if(Math.abs(rv[i]-m.locationRadius)<2)ri=i;s.radius.setSelection(ri);c.addView(s.radius,new LinearLayout.LayoutParams(-1,dp(a,48)));
  if(id>0){Button guests=new Button(a);guests.setAllCaps(false);guests.setText(tr(a,"👥 إدارة المدعوين وحالة الحضور","👥 Manage invitations & attendance"));c.addView(guests,new LinearLayout.LayoutParams(-1,dp(a,50)));guests.setOnClickListener(v->a.startActivity(new Intent(a,GuestManagerActivity.class).putExtra("event_id",id)));}
 }
 public static void onActivityResult(Activity a,int req,int result,Intent data){State s=STATES.get(a);if(s==null||req!=9404||result!=Activity.RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();try{a.getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}s.voiceUri=u.toString();if(s.voice!=null)s.voice.setText(tr(a,"✓ ملاحظة صوتية مرفقة","✓ Voice note attached"));}
 public static void applyTemplate(Activity a,Spinner cat,Spinner rec,CheckBox[] checks,int[] values){Intent in=a.getIntent();if(!in.hasExtra("template_category"))return;String c=in.getStringExtra("template_category"),r=in.getStringExtra("template_recurrence"),csv=in.getStringExtra("template_reminders");cat.setSelection(Categories.indexOf(c));rec.setSelection(Recurrence.indexOf(r));Set<Integer> set=new HashSet<>();if(csv!=null)for(String x:csv.split(","))try{set.add(Integer.parseInt(x));}catch(Exception ignored){}for(int i=0;i<checks.length;i++)checks[i].setChecked(set.contains(values[i]));}
 public static boolean duplicate(Activity a,long editingId,String title,long when){for(EventStore.Event e:EventStore.load(a)){if(e.id==editingId)continue;if(e.title.trim().equalsIgnoreCase(title.trim())&&Math.abs(e.eventTime-when)<6*3600000L)return true;}return false;}
 public static void afterSave(Activity a,EventStore.Event e){State s=STATES.get(a);if(s==null||e==null)return;V4Meta.Meta m=V4Meta.get(a,e.id);if(m.createdAt==0)m.createdAt=System.currentTimeMillis();m.tag=V4Meta.TAG_CODES[Math.max(0,s.tag.getSelectedItemPosition())];m.timeZoneId=String.valueOf(s.tz.getSelectedItem());m.smartReminder=s.smart.isChecked();m.webUrl=s.web.getText().toString().trim();m.phone=s.phone.getText().toString().trim();m.contactName=s.contact.getText().toString().trim();m.voiceNoteUri=s.voiceUri;String[] lt={"none","arrive","leave"};m.locationReminder=lt[Math.max(0,s.locType.getSelectedItemPosition())];float[] rv={100,250,500,1000};m.locationRadius=rv[Math.max(0,s.radius.getSelectedItemPosition())];double[] xy=parseGeo(e.locationUrl);if(xy!=null){m.locationLat=xy[0];m.locationLng=xy[1];}V4Meta.put(a,e.id,m);V4Log.history(a,e.id,"save","Event saved/updated");LocationReminderScheduler.schedule(a);}
 public static void applySmart(Activity a,String cat,CheckBox[] checks,int[] values){Set<Integer> s=new HashSet<>();if("birthday".equals(cat)){s.add(10080);s.add(1440);}else if("travel".equals(cat)){s.add(1440);s.add(180);}else if("meeting".equals(cat)){s.add(60);s.add(15);}else if("mawlid".equals(cat)||"eid_fitr".equals(cat)||"eid_adha".equals(cat)||"martyrdom".equals(cat)||"fatiha".equals(cat)){String raw=a.getSharedPreferences("munasabati_v4",0).getString("religious_reminders","1440,60");for(String x:raw.split(","))try{s.add(Integer.parseInt(x));}catch(Exception ignored){}}else{s.add(60);s.add(30);}for(int i=0;i<checks.length;i++)checks[i].setChecked(s.contains(values[i]));Toast.makeText(a,tr(a,"تم تطبيق التنبيهات الذكية","Smart reminders applied"),Toast.LENGTH_SHORT).show();}
 private static double[] parseGeo(String s){try{if(s==null||!s.startsWith("geo:"))return null;String p=s.substring(4).split("\\?")[0];String[] a=p.split(",");return new double[]{Double.parseDouble(a[0]),Double.parseDouble(a[1])};}catch(Exception e){return null;}}
 private static TextView label(Activity a,String s){TextView t=t(a,s,12,true);t.setPadding(0,dp(a,7),0,dp(a,3));return t;}private static EditText input(Activity a,String hint,String val){EditText e=new EditText(a);e.setHint(hint);e.setText(val);e.setSingleLine(true);e.setTextSize(13);e.setBackground(bg(a,Color.rgb(247,249,250),12));e.setPadding(dp(a,10),0,dp(a,10),0);return e;}private static TextView t(Activity a,String s,int z,boolean b){TextView t=new TextView(a);t.setText(s);t.setTextSize(z);if(b)t.setTypeface(null,1);return t;}
 private V4EditorHooks(){}
}
