package com.rafat.munasabati;

import android.app.Activity;import android.content.*;import android.graphics.*;import android.net.Uri;import com.google.zxing.*;import com.google.zxing.common.BitMatrix;import com.google.zxing.qrcode.QRCodeWriter;import java.io.*;import java.text.SimpleDateFormat;import java.util.*;

public final class V4Share{
 public static String text(Activity a,EventStore.Event e){V4Meta.Meta m=V4Meta.get(a,e.id);return e.title+"\n"+Categories.label(a,e.category)+"\n"+DateTools.gregorianShort(a,e.eventTime)+" • "+DateTools.time(a,e.eventTime)+"\n☾ "+DateTools.hijri(a,e.eventTime)+(e.locationName.isEmpty()?"":"\n📍 "+e.locationName)+(m.webUrl.isEmpty()?"":"\n🔗 "+m.webUrl)+(m.phone.isEmpty()?"":"\n☎ "+m.phone);}
 public static void shareCard(Activity a,EventStore.Event e){try{Bitmap b=Bitmap.createBitmap(1080,1080,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(Color.rgb(244,247,249));Paint p=new Paint(1);p.setColor(Color.rgb(25,91,86));c.drawRoundRect(60,60,1020,1020,55,55,p);p.setColor(Color.WHITE);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(58);c.drawText(e.title,540,250,p);p.setTextSize(38);p.setTypeface(Typeface.DEFAULT);c.drawText(Categories.icon(e.category)+"  "+Categories.label(a,e.category),540,350,p);p.setTextSize(40);c.drawText(DateTools.gregorianShort(a,e.eventTime)+"  •  "+DateTools.time(a,e.eventTime),540,465,p);p.setTextSize(34);c.drawText("☾  "+DateTools.hijri(a,e.eventTime),540,540,p);if(!e.locationName.isEmpty())c.drawText("📍  "+e.locationName,540,650,p);p.setColor(Color.rgb(255,235,180));p.setTextSize(30);c.drawText(AppSettings.tr(a,"مناسباتي","Munasabati"),540,900,p);shareBitmap(a,b,"event_card_"+e.id+".png");}catch(Exception ex){V4Log.error(a,"share_card",ex.toString());}}
 public static void shareQr(Activity a,EventStore.Event e){try{String payload="MUNASABATI|"+e.title+"|"+e.eventTime+"|"+e.locationName;BitMatrix m=new QRCodeWriter().encode(payload,BarcodeFormat.QR_CODE,800,800);Bitmap q=Bitmap.createBitmap(800,800,Bitmap.Config.RGB_565);for(int y=0;y<800;y++)for(int x=0;x<800;x++)q.setPixel(x,y,m.get(x,y)?Color.BLACK:Color.WHITE);shareBitmap(a,q,"event_qr_"+e.id+".png");}catch(Exception ex){V4Log.error(a,"share_qr",ex.toString());}}
 public static void shareIcs(Activity a,EventStore.Event e){try{File f=file(a,"event_"+e.id+".ics");SimpleDateFormat s=new SimpleDateFormat("yyyyMMdd'T'HHmmss",Locale.US);s.setTimeZone(TimeZone.getTimeZone("UTC"));String start=s.format(new Date(e.eventTime));String end=s.format(new Date(e.eventTime+3600000));String ics="BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Munasabati//EN\r\nBEGIN:VEVENT\r\nUID:"+e.id+"@munasabati\r\nDTSTART:"+start+"Z\r\nDTEND:"+end+"Z\r\nSUMMARY:"+esc(e.title)+"\r\nLOCATION:"+esc(e.locationName)+"\r\nDESCRIPTION:"+esc(e.details)+"\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n";try(FileOutputStream o=new FileOutputStream(f)){o.write(ics.getBytes("UTF-8"));}shareFile(a,f,"text/calendar");}catch(Exception ex){V4Log.error(a,"share_ics",ex.toString());}}
 private static void shareBitmap(Activity a,Bitmap b,String name)throws Exception{File f=file(a,name);try(FileOutputStream o=new FileOutputStream(f)){b.compress(Bitmap.CompressFormat.PNG,95,o);}shareFile(a,f,"image/png");}
 private static File file(Activity a,String n){File d=new File(a.getFilesDir(),"attachments");d.mkdirs();return new File(d,n);}
 private static void shareFile(Activity a,File f,String mime){Uri u=Uri.parse("content://"+AttachmentProvider.AUTHORITY+"/"+Uri.encode(f.getName()));Intent i=new Intent(Intent.ACTION_SEND);i.setType(mime);i.putExtra(Intent.EXTRA_STREAM,u);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);a.startActivity(Intent.createChooser(i,AppSettings.tr(a,"مشاركة","Share")));}
 private static String esc(String s){return(s==null?"":s).replace("\\","\\\\").replace(";","\\;").replace(",","\\,").replace("\n","\\n");}private V4Share(){}
}
