plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rafat.wifimonitor'
    compileSdk 35

    defaultConfig {
        applicationId "com.rafat.wifimonitor"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
